### ISSUE TITLE
Irc Module needs to be updated to take its configuration from the configuration package

### ISSUE THREAD

**Issue by setkeh** [thesetkehproject/ana#8]
The configuration should be able to more robustly globalise and modularise the configuration of ana and the irc module will now need to be updated to take its configuration from the new module.

**Comment by setkeh** [comment]
Looks like i might have re write the irc module connection stuff it appears something has changed or im not remembering correctly but i think this was working lol.

```
/usr/lib/go/bin/go run /home/setkeh/gocode/src/github.com/thesetkehproject/ana/main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x586fe4]

goroutine 1 [running]:
github.com/thoj/go-ircevent.(*Connection).Connect(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/setkeh/gocode/src/github.com/thoj/go-ircevent/irc.go:374 +0x64
github.com/thesetkehproject/ana/irc.Connect(0xc4200109f0, 0x9)
	/home/setkeh/gocode/src/github.com/thesetkehproject/ana/irc/irc.go:17 +0x7e
main.main()
	/home/setkeh/gocode/src/github.com/thesetkehproject/ana/main.go:16 +0xbd
exit status 2

Process finished with exit code 1
```

**Comment by setkeh** [comment]
Go-ircevent Also now Supports SSL and SSL will be hard Coded on while im troubleshooting the irc Connector issue.

**Comment by setkeh** [comment]
The IRC module is now taking its configuration as a Parameter its a little messy at the moment but ill open a new issue for that as the irc module has had a complete overhaul at this point.
